# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Sukumar | Blog
tagline:          'Blog of technology explorer.'
description:      'I blog ocationally about my projects and opinion on new and pre-released technologies. contact me <a href="https://twitter.com/sukumargv" target="_blank">@mdo</a>.'
url:              http://sukumar.me
baseurl:          /

author:
  name:           'Sukumar'
  url:            https://twitter.com/sukumargv

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sukumargv/sukumargv.github.io
